/* global describe, it */

'use strict';

var assert = require('assert'),
	Rx = require('rx'),
	parseCoffee = require('..'),
	CS = require('coffee-script-redux');

it('test', function (done) {
	var file = {path: 'file.coffee', contents: 'a = 1'},
		input = [file],
		expected = ['// Generated by CoffeeScript 2.0.0-beta8\nvar a;\na = 1;'];

	// simulating file sequence and applying transformation
	parseCoffee()(Rx.Observable.fromArray(input))
	// checking against array of expected results iteratively
	.zip(expected, function (file, code) {
		assert.equal(CS.js(file.program, {bare: true}), code);
	})
	// subscribing to check results
	.subscribe(function () {}, done, done);
});
